version: '3.2'
services:
  db:
    image: ${IMAGE_DB:-mcr.microsoft.com/mssql/server}:${TAG_DB:-2022-latest}
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD:-pass@word1}
    ports:
      - 1433:1433
    volumes:
      - db:/var/opt/mssql/data

  app:
    image: ghcr.io/whizus/job-interview-task-trees-of-data:latest
    environment:
      - Seed=${Seed:-true}
      - ConnectionStrings__AppDbContext=Server=db,1433; Database=app;Trusted_Connection=False;Encrypt=False;User Id=sa;Password=pass@word1
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db: